# create namespace
apiVersion: v1
kind: Namespace
metadata:
  name: corewar-prod
---

# create tls secret
apiVersion: v1
kind: Secret
metadata:
  name: ozyria-tls
  namespace: corewar-prod
type: kubernetes.io/tls
data:
  tls.crt: <base64-encoded-cert>
  tls.key: <base64-encoded-key>
---

# create docker registry secret
apiVersion: v1
kind: Secret
metadata:
  name: ozyria-registry-secret
  namespace: corewar-staging
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <base64-encoded-docker-config>
---

# create data-credentials secret
apiVersion: v1
kind: Secret
metadata:
  name: data-credentials
  namespace: corewar-prod
type: Opaque
data:
  postgres-password: <base64-encoded-password>
  redis-password: <base64-encoded-password>
  jwt-secret: <base64-encoded-secret>

---
# create postgres pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: corewar-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn

---
# create redis pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: corewar-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# create postgres deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: corewar-prod
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: corewar
            - name: POSTGRES_USER
              value: corewar
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: data-credentials
                  key: postgres-password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

---
# create postgres service
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: corewar-prod
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
  clusterIP: None

---
# create redis configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: corewar-prod
data:
  redis.conf: |
    appendonly yes
    appendfsync everysec

    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 128mb

    save 60 1000
    save 300 10
  
---
# create redis deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: corewar-prod
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: data-credentials
                  key: redis-password
          args:
            - "redis-server"
            - "/usr/local/etc/redis/redis.conf"
            - "--requirepass"
            - "<redis-password>"
          volumeMounts:
            - name: redis-config
              mountPath: /usr/local/etc/redis/
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-config
          configMap:
            name: redis-config
            items:
              - key: redis.conf
                path: redis.conf
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data

---
# create redis service
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: corewar-prod
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
  clusterIP: None

---
# create exec-app deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exec-app
  namespace: corewar-prod
spec:
  selector:
    matchLabels:
      app: exec-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: exec-app
    spec:
      imagePullSecrets:
        - name: ozyria-registry-secret
      containers:
        - name: exec-app
          image: registry.ozyria.fr/corewar/exec-app:release-0.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: exec-app-config
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 5

---
# create exec-app service
apiVersion: v1
kind: Service
metadata:
  name: exec-app
  namespace: corewar-prod
spec:
  selector:
    app: exec-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---
# create back-app deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-app
  namespace: corewar-prod
spec:
  selector:
    matchLabels:
      app: back-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: back-app
    spec:
      imagePullSecrets:
        - name: ozyria-registry-secret
      containers:
        - name: back-app
          image: registry.ozyria.fr/corewar/back-app:release-0.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: back-app-config
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 5

---
# create back-app service
apiVersion: v1
kind: Service
metadata:
  name: back-app
  namespace: corewar-prod
spec:
  selector:
    app: back-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---
# create front-app deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-app
  namespace: corewar-prod
spec:
  selector:
    matchLabels:
      app: front-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: front-app
    spec:
      imagePullSecrets:
        - name: ozyria-registry-secret
      containers:
        - name: front-app
          image: registry.ozyria.fr/corewar/front-app:release-0.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5

---
# create front-app service
apiVersion: v1
kind: Service
metadata:
  name: front-app
  namespace: corewar-prod
spec:
  selector:
    app: front-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
# create apps ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: apps-ingress
    namespace: corewar-prod
    annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
    tls:
        - hosts:
              - corewar.ozyria.fr
              - corewar-api.ozyria.fr
              - corewar-exec.ozyria.fr
          secretName: ozyria-tls
    rules:
        - host: corewar.ozyria.fr
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: front-app
                            port:
                                number: 80
        - host: corewar-api.ozyria.fr
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: back-app
                            port:
                                number: 80
        - host: corewar-exec.ozyria.fr
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: exec-app
                            port:
                                number: 80
