apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: corewar-prod
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        job-name: db-migration
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: onorahubleur/corewar-migrate-job:release-{{VERSION}}
          envFrom:
            - configMapRef:
                name: back-app-config