# create exec-app deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exec-app
  namespace: corewar-prod
spec:
  selector:
    matchLabels:
      app: exec-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: exec-app
    spec:
      imagePullSecrets:
        - name: ozyria-registry-secret
      containers:
        - name: exec-app
          image: registry.ozyria.fr/corewar/exec-app:release-{{VERSION}}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: exec-app-config
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 5