# create back-app deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-app
  namespace: corewar-prod
spec:
  selector:
    matchLabels:
      app: back-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: back-app
    spec:
      imagePullSecrets:
        - name: ozyria-registry-secret
      containers:
        - name: back-app
          image: registry.ozyria.fr/corewar/back-app:release-{{VERSION}}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: back-app-config
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 5
          volumeMounts:
            - name: app-uploads
              mountPath: /corewar-back-app/uploads
      volumes:
        - name: app-uploads
          persistentVolumeClaim:
            claimName: app-uploads