packages:
    - apps/*
    - libs/*

onlyBuiltDependencies:
    - '@prisma/client'
    - '@prisma/engines'
    - esbuild
    - msgpackr-extract
    - prisma

syncInjectedDepsAfterScripts:
    - build
injectWorkspacePackages: true
