services:
    databse:
        image: postgres:latest
        container_name: postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - '5432:5432'
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        restart: always

    redis:
        image: redis:latest
        container_name: redis
        command: redis-server --requirepass ${REDIS_PASSWORD}
        ports:
            - '6379:6379'
        volumes:
            - ./redis_data:/data
        restart: always
