apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: corewar-staging
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        job-name: db-migration
    spec:
      imagePullSecrets:
        - name: ozyria-registry-secret
      restartPolicy: Never
      containers:
        - name: migrate
          image: registry.ozyria.fr/corewar/migrate-job:staging-{{COMMIT_SHA}}
          envFrom:
            - configMapRef:
                name: back-app-config