name: Build and push Docker images

on:
    workflow_call:
        inputs:
            buildArgs:
                required: true
                type: string
                description: 'Build arguments, multiline string with each argument on a new line'
            tags:
                required: true
                type: string
                description: 'Tags for the image, multiline string with each tag on a new line'
        secrets:
            DOCKER_USERNAME:
                required: true
            DOCKER_PASSWORD:
                required: true

jobs:
    prepare-tags:
        name: Prepare tags
        runs-on: ubuntu-latest
        outputs:
            exec_app_tags: ${{ steps.set-tags.outputs.exec_app_tags }}
            migrate_job_tags: ${{ steps.set-tags.outputs.migrate_job_tags }}
            back_app_tags: ${{ steps.set-tags.outputs.back_app_tags }}
            front_app_tags: ${{ steps.set-tags.outputs.front_app_tags }}
        steps:
            - name: Set up tags
              id: set-tags
              run: |
                  tags="${{ inputs.tags }}"
                  exec_app_tags=""
                  migrate_job_tags=""
                  back_app_tags=""
                  front_app_tags=""
                  while IFS= read -r tag; do
                      if [ -z "$tag" ]; then
                          continue
                      fi
                      exec_app_tags="$exec_app_tags,registry.ozyria.fr/corewar/exec-app:$tag"
                      migrate_job_tags="$migrate_job_tags,registry.ozyria.fr/corewar/migrate-job:$tag"
                      back_app_tags="$back_app_tags,registry.ozyria.fr/corewar/back-app:$tag"
                      front_app_tags="$front_app_tags,registry.ozyria.fr/corewar/front-app:$tag"
                  done <<< "$tags"
                  echo "exec_app_tags=${exec_app_tags:1}" >> $GITHUB_OUTPUT
                  echo "migrate_job_tags=${migrate_job_tags:1}" >> $GITHUB_OUTPUT
                  echo "back_app_tags=${back_app_tags:1}" >> $GITHUB_OUTPUT
                  echo "front_app_tags=${front_app_tags:1}" >> $GITHUB_OUTPUT

    build-and-push:
        name: Build and push images
        needs: prepare-tags
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Build common stage
              uses: docker/build-push-action@v6
              with:
                  context: ./
                  file: ./Dockerfile
                  push: false
                  target: build
                  platforms: linux/amd64
                  build-args: ${{ inputs.buildArgs }}
                  tags: |
                      corewar/common:latest

            - name: Log in to Docker Registry
              uses: docker/login-action@v3
              with:
                  registry: registry.ozyria.fr
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push exec-app image
              uses: docker/build-push-action@v6
              with:
                  context: ./
                  file: ./Dockerfile
                  push: true
                  target: exec-app
                  platforms: linux/amd64
                  build-args: ${{ inputs.buildArgs }}
                  tags: ${{ needs.prepare-tags.outputs.exec_app_tags }}

            - name: Build and push back-app image
              uses: docker/build-push-action@v6
              with:
                  context: ./
                  file: ./Dockerfile
                  push: true
                  target: back-app
                  platforms: linux/amd64
                  build-args: ${{ inputs.buildArgs }}
                  tags: ${{ needs.prepare-tags.outputs.back_app_tags }}

            - name: Build and push migration job image
              uses: docker/build-push-action@v6
              with:
                  context: ./
                  file: ./Dockerfile
                  push: true
                  target: migrate
                  platforms: linux/amd64
                  build-args: ${{ inputs.buildArgs }}
                  tags: ${{ needs.prepare-tags.outputs.migrate_job_tags }}

            - name: Build and push front-app image
              uses: docker/build-push-action@v6
              with:
                  context: ./
                  file: ./Dockerfile
                  push: true
                  target: front-app
                  platforms: linux/amd64
                  build-args: ${{ inputs.buildArgs }}
                  tags: ${{ needs.prepare-tags.outputs.front_app_tags }}
