name: MR Close

on:
    pull_request:
        types: [closed]

jobs:
    delete-mr-namespace:
        name: Delete MR Namespace

        runs-on: ubuntu-24.04

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up kubeconfig
              run: |
                mkdir -p ~/.kube
                echo ${{ secrets.KUBE_CONFIG_DATA }} | base64 -d > ~/.kube/config

            - name: Delete MR Namespace
              run: |
                  kubectl delete namespace corewar-mr-${{ github.event.pull_request.number }} --ignore-not-found --insecure-skip-tls-verify
