name: MR workflow

env:
    PNPM_VERSION: '10.12.4'
    NODE_VERSION: '23'

on:
    pull_request:
        types: [opened, synchronize, reopened, closed]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
    cancel-in-progress: true

jobs:
    lint:
        name: Lint
        if: ${{ github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.action == 'reopened' }}
        uses: ./.github/workflows/lint.yaml

    variables:
        name: Store variables
        if: ${{ github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.action == 'reopened' }}

        runs-on: ubuntu-24.04
        outputs:
            sha_short: ${{ steps.vars.outputs.sha_short }}

        steps:
            - name: Compute short SHA
              id: vars
              run: echo "sha_short=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

    prepare-tags:
        name: Prepare tags
        needs:
            - variables
        runs-on: ubuntu-24.04
        outputs:
            tags: ${{ steps.set-tags.outputs.tags }}
        steps:
            - name: Compute tags
              id: set-tags
              run: |
                  PR_NUMBER=${{ github.event.pull_request.number }}
                  SHA=${{ needs.variables.outputs.sha_short }}

                  TAG_LIST="mr-${PR_NUMBER}-latest mr-${PR_NUMBER}-${SHA}"

                  echo "Tags: $TAG_LIST"
                  echo "tags=$TAG_LIST" >> $GITHUB_OUTPUT

    build:
        name: Build apps
        needs:
            - lint
            - prepare-tags

        uses: ./.github/workflows/build-images.yaml
        with:
            buildArgs: |
                MR_ID=${{ github.event.pull_request.number }}
                ENVIRONMENT=mr
            tags: ${{ needs.prepare-tags.outputs.tags }}
        secrets:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    deploy:
        name: Deploy to Kubernetes
        needs:
            - build
            - variables
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up kubeconfig
              run: |
                  mkdir -p ~/.kube
                  echo ${{ secrets.KUBE_CONFIG_DATA }} | base64 -d > ~/.kube/config

            - name: Deploy
              run: |
                  ./infra/deploy_mr.sh ${{ github.event.pull_request.number }} ${{ secrets.API_CLIENT_ID }} ${{ secrets.API_CLIENT_SECRET }} ${{ secrets.TLS_CERT }} ${{ secrets.TLS_KEY }} ${{ needs.variables.outputs.sha_short }} ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}

            - name: Comment MR with deployment info
              uses: mshick/add-pr-comment@v2
              with:
                  allow-repeats: true
                  message: |
                      🚀 Deployment Info

                      The MR has been deployed to a temporary environment for testing

                      - Frontend: `https://mr${{ github.event.pull_request.number }}-corewar.ozyria.fr`
                      - Backend: `https://mr${{ github.event.pull_request.number }}-corewar-api.ozyria.fr`
                      - Exec API: `https://mr${{ github.event.pull_request.number }}-corewar-exec.ozyria.fr`

                      > Note: The environment will be automatically deleted when the MR is closed

    clean-old-images:
        name: Clean old MR images
        needs: build
        uses: ./.github/workflows/clean-old-images.yaml
        with:
            tagPrefix: mr-${{ github.event.pull_request.number }}-
            keepCount: 10
        secrets:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    delete-mr-environment:
        name: Delete MR environment
        if: ${{ github.event.action == 'closed' }}

        runs-on: ubuntu-24.04

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up kubeconfig
              run: |
                  mkdir -p ~/.kube
                  echo ${{ secrets.KUBE_CONFIG_DATA }} | base64 -d > ~/.kube/config

            - name: Delete MR Namespace
              run: |
                  kubectl delete namespace corewar-mr-${{ github.event.pull_request.number }} --ignore-not-found --insecure-skip-tls-verify

            - name: Comment MR with cleanup info
              uses: mshick/add-pr-comment@v2
              with:
                  allow-repeats: true
                  message: |
                      🗑️ Cleanup Info

                      The temporary environment for this MR has been deleted.

    delete-mr-images:
        name: Delete MR images
        needs: delete-mr-environment
        uses: ./.github/workflows/clean-old-images.yaml
        with:
            tagPrefix: mr-${{ github.event.pull_request.number }}-
            keepCount: 0
        secrets:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
