name: Push pipeline

env:
    PNPM_VERSION: '8'
    NODE_VERSION: '20'

on:
    push:
    workflow_dispatch:

jobs:
    filter:
        name: Filter changed paths
        runs-on: ubuntu-24.04

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Filter changes
              id: filter
              uses: dorny/paths-filter@v3
              with:
                  filters: |
                      front-app:
                        - 'front-app/**'
                      back-app:
                        - 'back-app/**'

        outputs:
            front-app: ${{ steps.filter.outputs.front-app }}
            back-app: ${{ steps.filter.outputs.back-app }}

    lint-front-app:
        name: Lint front-app
        needs: filter
        if: ${{ needs.filter.outputs.front-app == 'true' || github.event_name == 'workflow_dispatch' }}

        runs-on: ubuntu-24.04

        defaults:
            run:
                working-directory: front-app

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: ${{ env.PNPM_VERSION }}
                  run_install: false

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: 'pnpm'
                  cache-dependency-path: './front-app/pnpm-lock.yaml'

            - name: Install dependencies
              run: pnpm install

            - name: Lint app
              run: pnpm lint

    lint-back-app:
        name: Lint back-app
        needs: filter
        if: ${{ needs.filter.outputs.back-app == 'true' || github.event_name == 'workflow_dispatch' }}

        runs-on: ubuntu-24.04

        defaults:
            run:
                working-directory: back-app

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: ${{ env.PNPM_VERSION }}
                  run_install: false

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: 'pnpm'
                  cache-dependency-path: './back-app/pnpm-lock.yaml'

            - name: Install dependencies
              run: pnpm install

            - name: Lint app
              run: pnpm lint
